---
######################### Standing Desk CUSTOM PCB ################################
substitutions:
  device_name: standingdesk
  heightoffsetincm: '0.3'

esp32:
  board: esp32-c3-devkitm-1

esphome:
  name: ${device_name}
  includes:
    - standingdesk_height.h

wifi:
  fast_connect: true
  domain: !secret iotdomain

  networks:
    - ssid: !secret wifissid
      password: !secret wifipass

# Enable logging
logger:

api:
  encryption:
    key: YOURKEYHERE

ota:
  platform: esphome
  password: !secret espotapass

time:
  - platform: homeassistant
    id: homeassistant_time


output:
  - platform: gpio
    id: pin8
    pin:
      number: GPIO2
      inverted: true

  - platform: gpio
    id: pin7
    pin:
      number: GPIO1
      inverted: true

  - platform: gpio
    id: pin6
    pin:
      number: GPIO3
      inverted: true

number:
  - platform: template
    name: ${device_name}_direction_value
    id: target_movement_cm
    optimistic: true
    unit_of_measurement: 'cm'
    icon: mdi:altimeter
    min_value: 1
    max_value: 70
    step: 1
    initial_value: 10
    restore_value: false
    mode: 'box'

script:

- id: direction_down
  mode: single
  then:
    - logger.log: "Moving down"
    - output.turn_on: pin8
    - delay: !lambda "return float(id(target_movement_cm).state) * 275.2;"
    - output.turn_off: pin8

- id: direction_up
  mode: single
  then:
    - logger.log: "Moving up"
    - output.turn_on: pin7
    - delay: !lambda "return float(id(target_movement_cm).state) * 298.5;"
    - output.turn_off: pin7

- id: position_m1
  mode: single
  then:
    - logger.log: "Memory 1: Standing position"
    - output.turn_on: pin8
    - output.turn_on: pin7
    - delay: 500ms
    - output.turn_off: pin8
    - output.turn_off: pin7

- id: position_m2
  mode: single
  then:
    - logger.log: "Memory 2: Sitting position"
    - output.turn_on: pin6
    - delay: 500ms
    - output.turn_off: pin6

- id: position_m3
  mode: single
  then:
    - logger.log: "Memory 3"
    - output.turn_on: pin8
    - output.turn_on: pin6
    - delay: 500ms
    - output.turn_off: pin8
    - output.turn_off: pin6

- id: position_m4
  mode: single
  then:
    - logger.log: "Memory 4"
    - output.turn_on: pin7
    - output.turn_on: pin6
    - delay: 500ms
    - output.turn_off: pin7
    - output.turn_off: pin6


button:
  - platform: restart
    name: ${device_name}_restart
    id: restart_esp

  - platform: template
    name: ${device_name}_direction_down
    icon: "mdi:arrow-down-bold-outline"
    on_press:
      - script.execute: direction_down
  
  - platform: template
    name: ${device_name}_direction_up
    icon: "mdi:arrow-up-bold-outline"
    on_press:
      - script.execute: direction_up
  
  - platform: template
    name: ${device_name}_position_standing
    icon: "mdi:walk"
    on_press:
      - script.execute: position_m1
  
  - platform: template
    name: ${device_name}_position_sitting
    icon: "mdi:sofa-single-outline"
    on_press:
      - script.execute: position_m2
  
  - platform: template
    name: ${device_name}_position_m3
    on_press:
      - script.execute: position_m3
  
  - platform: template
    name: ${device_name}_position_m4
    on_press:
      - script.execute: position_m4

uart:
  id: desk_uart
  baud_rate: 9600
  rx_pin:
    number: GPIO4
    inverted: false

sensor:
  - platform: custom
    lambda: |-
      auto desk_height_sensor = new DeskHeightSensor(id(desk_uart));
      App.register_component(desk_height_sensor);
      return {desk_height_sensor};
    sensors:
      id: "desk_height"
      name: ${device_name}_deskheight
      unit_of_measurement: cm
      accuracy_decimals: 1
      icon: "mdi:counter"
      filters:
        - offset: ${heightoffsetincm}
    
